import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const [runJsonPath, destination] = process.argv.slice(2);
if (!runJsonPath || !destination) throw new Error("Usage: node scripts/build_field_mapping.mjs <run.json> <destination>");

const result = JSON.parse(await fs.readFile(runJsonPath, "utf8"));
const headers = ["模块", "来源文件", "经销商原始字段", "EC101标准字段", "字段关系", "来源类型", "重要度", "证据等级", "状态", "说明"];
const workbook = Workbook.create();
const sheet = workbook.worksheets.add("字段映射");
sheet.showGridLines = false;
sheet.getRange("A2").values = [["EC101 标准字段映射表"]];
sheet.getRange("A2").format.font = { name: "Arial", size: 15, bold: true, color: "#1F4E78" };
sheet.getRange("A3").values = [[`${result.platform}-${result.dealer}｜经销商原始字段全集 ∪ EC101 V1 标准字段全集；字段可达不等于平台能力结论。`]];
sheet.getRange("A3").format.font = { name: "Arial", size: 10, italic: true, color: "#5B6573" };
sheet.getRangeByIndexes(5, 0, 1, headers.length).values = [headers];
const head = sheet.getRangeByIndexes(5, 0, 1, headers.length);
head.format = { fill: "#1F4E78", font: { name: "Arial", size: 10, bold: true, color: "#FFFFFF" }, horizontalAlignment: "center", verticalAlignment: "center", wrapText: true, borders: { preset: "all", style: "thin", color: "#FFFFFF" } };
const rows = result.field_mappings.map((row) => headers.map((header) => row[header] ?? ""));
const body = sheet.getRangeByIndexes(6, 0, rows.length, headers.length);
body.values = rows;
body.format.font = { name: "Arial", size: 10, color: "#1F2937" };
body.format.wrapText = true;
body.format.verticalAlignment = "center";
body.format.borders = { preset: "inside", style: "thin", color: "#B7C9D6" };
body.format.autofitRows();
const widths = [16, 34, 28, 26, 16, 18, 10, 14, 18, 42];
for (let column = 0; column < widths.length; column += 1) sheet.getRangeByIndexes(5, column, rows.length + 1, 1).format.columnWidth = widths[column];
sheet.freezePanes.freezeRows(6);
workbook.recalculate();
const check = await workbook.inspect({ kind: "table", sheetId: "字段映射", range: "A2:J14", include: "values", tableMaxRows: 14, tableMaxCols: 10 });
console.log(check.ndjson);
const errors = await workbook.inspect({ kind: "match", searchTerm: "#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A", options: { useRegex: true, maxResults: 100 }, summary: "formula errors" });
console.log(errors.ndjson);
const preview = await workbook.render({ sheetName: "字段映射", range: "A1:J20", scale: 1, format: "png" });
const previewDir = path.join(path.dirname(destination), "_previews");
await fs.mkdir(previewDir, { recursive: true });
await fs.writeFile(path.join(previewDir, "标准字段映射表.xlsx.png"), new Uint8Array(await preview.arrayBuffer()));
const output = await SpreadsheetFile.exportXlsx(workbook);
await output.save(destination);
